### ISSUE TITLE
Build variants test artifact could be missing

### ISSUE THREAD

**Issue by evasyuk** [mutexkid/android-studio-robolectric-example#5]
For the first time trying to choose "Test Artifact: Unit tests" option could be unavailable due to missing option in Settings
Solution: Settings(Ctrl+Alt+S) -> Gradle -> Experimental -> Mark "Enable Unit test support" option

Details available at: http://tools.android.com/tech-docs/unit-testing-support

**Comment by mutexkid** [comment]
This should no longer be required in the most recent version of Android Studio (1.2 RC should include this enabled by default).

**Comment by ZengTianShengZ** [comment]
我跟着你说的设置了。还是不行，怎么办

**Comment by madhanmallow** [comment]
@mutexkid: I'm using Android Studio 2.2.3, but I can't find the Test Artifact selector. Also in Settings(Ctrl+Alt+S) -> Gradle -> Experimental -> Mark "Enable Unit test support" option, I can't find the "Enable Unit test support" option.

**Comment by tir38** [comment]
@madhanmallow that feature is no longer experimental. It's baked in to Android Studio. No way (or need) to turn it off.

**Comment by madhanmallow** [comment]
@tir38 Thanks for the info.
