### ISSUE TITLE
org/sonatype/oss/oss-parent/7/oss-parent-7.pom missing

### ISSUE THREAD

**Issue by SebastianKapunkt** [mutexkid/android-studio-robolectric-example#6]
when executing test its fails with error: 

    Downloading: org/sonatype/oss/oss-parent/7/oss-parent-7.pom from repository sonatype at      https://oss.sonatype.org/content/groups/public/
    Unable to locate resource in repository
    [INFO] Unable to find resource 'org.sonatype.oss:oss-parent:pom:7' in repository sonatype (https://oss.sonatype.org/content/groups/public/)
    Downloading: org/sonatype/oss/oss-parent/7/oss-parent-7.pom from repository central at    http://repo1.maven.org/maven2
    Error transferring file: Connection refused: connect
    [WARNING] Unable to get resource 'org.sonatype.oss:oss-parent:pom:7' from repository central (http://repo1.maven.org/maven2): Error transferring file: Connection refused: connect

and yes when looking up: https://oss.sonatype.org/content/groups/public/org/sonatype/oss/oss-parent/

there is no 7, only 8 and 9

**Comment by mutexkid** [comment]
Hi sebastian, this looks like a problem perhaps on your side - did you ensure you've got a good working network connection?

**Comment by priyaranjan061** [comment]
having similar problem -not able to create folder maned '9' anywhere in my win 7 32 bit.
unzip: android-studio-ide-162.3764568-windows32.zip
not able to get --
android-studio-ide-162.3764568-windows32.zip
following file is not there
android-studio\gradle\m2repository\org\apache\apache\9\apache-9.pom
but   
 \7\apache-7.pom
is there
