### ISSUE TITLE
NoSuchMethod when running the test

### ISSUE THREAD

**Issue by elcioabrahao** [mutexkid/android-studio-robolectric-example#7]
Hi Josh !
First of all thanks by the example !
I m new to Roboletric and I m trying to run the example on Android Studio 1.2. The Android installations is new and there is no Roboletric plugins installed.
I just clone the project from Github, set the Build Variant to Unit Test, right click on the Project and run MyActivityTest. Before this I just resync the gradle build.
The problem is that the test throws a java.lang.NoSuchMethodException and I just can't find what is missing... Could you take a look on the error message ?

Console:

Testing started at 14:26 ...
14:26:58: Executing external tasks 'cleanTest test --tests com.example.joshskeen.myapplication.MyActivityTest'...
Configuration on demand is an incubating feature.:app:cleanTestUP-TO-DATE:app:preBuildUP-TO-DATE:app:preDebugBuildUP-TO-DATE:app:checkDebugManifest:app:prepareDebugDependencies:app:compileDebugAidlUP-TO-DATE:app:compileDebugRenderscriptUP-TO-DATE:app:generateDebugBuildConfigUP-TO-DATE:app:generateDebugAssetsUP-TO-DATE:app:mergeDebugAssetsUP-TO-DATE:app:generateDebugResValuesUP-TO-DATE:app:generateDebugResourcesUP-TO-DATE:app:mergeDebugResourcesUP-TO-DATE:app:processDebugManifestUP-TO-DATE:app:processDebugResourcesUP-TO-DATE:app:generateDebugSourcesUP-TO-DATE:app:compileDebugJava:app:preCompileDebugUnitTestJava:app:compileDebugUnitTestJava:app:compileDebugUnitTestSources:app:mockableAndroidJar:app:assembleDebugUnitTest:app:testDebugcom.example.joshskeen.myapplication.MyActivityTest > clickingClickMeButtonChangesHelloWorldText FAILED    java.lang.RuntimeException
        Caused by: java.lang.RuntimeException
            Caused by: java.lang.NoSuchMethodException
com.example.joshskeen.myapplication.MyActivityTest > myActivityAppearsAsExpectedInitially FAILED    java.lang.RuntimeException
        Caused by: java.lang.RuntimeException
            Caused by: java.lang.NoSuchMethodException
2 tests completed, 2 failed:app:testDebug FAILEDFAILURE: Build failed with an exception.* What went wrong:
Execution failed for task ':app:testDebug'.
> There were failing tests. See the report at: file:///home/elcio/AndroidStudioProjects/android-studio-robolectric-example/app/build/reports/tests/debug/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILEDTotal time: 10.662 secs
14:27:11: External tasks execution finished 'cleanTest test --tests com.example.joshskeen.myapplication.MyActivityTest'.

Gladle build:

Executing tasks: [cleanTest, test]

Configuration on demand is an incubating feature.
:app:cleanTest UP-TO-DATE
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:compileDebugJava
:app:preCompileDebugUnitTestJava
:app:compileDebugUnitTestJava
:app:compileDebugUnitTestSources
:app:mockableAndroidJar
:app:assembleDebugUnitTest
:app:testDebug

com.example.joshskeen.myapplication.MyActivityTest > clickingClickMeButtonChangesHelloWorldText FAILED
    java.lang.RuntimeException
        Caused by: java.lang.RuntimeException
            Caused by: java.lang.NoSuchMethodException

com.example.joshskeen.myapplication.MyActivityTest > myActivityAppearsAsExpectedInitially FAILED
    java.lang.RuntimeException
        Caused by: java.lang.RuntimeException
            Caused by: java.lang.NoSuchMethodException

2 tests completed, 2 failed

:app:testDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:testDebug'.
> There were failing tests. See the report at: file:///home/elcio/AndroidStudioProjects/android-studio-robolectric-example/app/build/reports/tests/debug/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 10.662 secs

Thanks,

Elcio A.

**Comment by mutexkid** [comment]
Hi Elcio, sorry for the late reply. Did you try running with the --stacktrace option enabled?
