### ISSUE TITLE
Worth mentioning alternatives

### ISSUE THREAD

**Issue by shurane** [mutexkid/android-studio-robolectric-example#8]
Robolectric has their own project on getting started with Robolectric and Android Studio. It's at [deckard/gradle](https://github.com/robolectric/deckard-gradle). Have you taken a look at it? Thought it was worth mentioning.

**Comment by mutexkid** [comment]
Hello! Thanks for the info - i've checked it out. 
1. This project focuses on only robolectric
2. The hope for this project ultimately is to show some more full featured robolectric tests.
